### ISSUE TITLE
Javascript error with Wordpress 4.7

### ISSUE THREAD

**Issue by akerd** [CaerCam/media-drag-n-drop-url#1]
Thank you for sharing, I would like to give you a feedback that it seems not working with Wordpress 4.7.
When I try to drag & drop and image from another Chrome page I see an javascript error:

```
Uncaught TypeError: e.dataTransfer.types.contains is not a function
    at mediadndurl.droppedText (mediadndurl-admin.js?ver=1.0:111)
```
in file mediadndurl-admin.js?ver=1.0:111

I will try to investigate too a little bit.

**Comment by akerd** [comment]
Ok found the problem and fixed in the following way:

```
 mediadndurl.droppedText = function(e) {

        var e = e || event;
        e.preventDefault();

        if ('link' === e.dataTransfer.dropEffect ||
            'move' === e.dataTransfer.dropEffect ||
            **_.contains(e.dataTransfer.types, 'text/html') ||
            _.contains(e.dataTransfer.types, 'text/uri-list')**) {

            e.preventDefault();

            var url = e.dataTransfer.getData('text/plain');
            mediadndurl.uploadFromURL(url);
        }
    };
```

Unfortunately there is a bigger problem after that and is about Access-Control-Allow-Origin for the XMLHttpRequest. The domains from where I am try to get the image URL and the domains where I want to upload it are different, and here really I have no idea how to solve it. Read a bit around and I don't now even if it possible without changing server parameters on source server.
